### PR TITLE
Keep C/C++ related files and rename only-go to only-code

### LINKED ISSUE #10: --only-go removes .c and .h files which breaks cgo packages
I know it's possible to not use this option, but it does cause problems in this case, so it might be worth thinking about how to deal with cgo.

### PR DESCRIPTION
**Pull request by chancez**
Closes #10

### CODE REVIEW

**Comment by chancez** [comment]
cc @sgotti

**Comment by sgotti** [comment]
@chancez  Thanks for doing this. Perhaps the tests should be improved adding some additional files to match these extensions.

**Comment by chancez** [comment]
@sgotti Added a bunch of files with the extensions into all the test cases. A bit verbose maybe, but at least it'll tell us if something breaks!

**Comment by sgotti** [comment]
@chancez. Great! Thanks a lot! LGTM.

**Comment by jonboulle** [comment]
@s-urbaniak ready for your follow up ☺️

**Pull request merged**
