### PR TITLE
implement configurable code suffix list

### PR DESCRIPTION
**Pull request by s-urbaniak**
This PR extends #11 by making the suffix list configurable.

We'd love to have this since we need this flexibility for rkt.

### CODE REVIEW

**Comment by sgotti** [comment]
@s-urbaniak just curious: which additional files are needed to make rkt build? Looks strange since go should only need `.go` files and the additional cgo files.

**Comment by s-urbaniak** [comment]
@sgotti thanks for the quick reply, for rkt it's `github.com/appc/spec/ace/*.json.in` files which we need to have vendored.

See https://github.com/coreos/rkt/pull/2735/commits/62cfe493a8f8970229045dc3ac3ac8e9736ef97a#diff-225c7ff27f2768d3bbb5cce782af9606R23 and the corrsponding PR https://github.com/coreos/rkt/pull/2735 to which I'd be happy to have a review from you :-)

Thanks for the tool btw!

**Comment by sgotti** [comment]
@s-urbaniak OK thanks, so it's a special case not needed for compilation. I don't have problem merging this. Pheraps, in a future, a repeatable option like `--keep regexp`  will be more powerful and fine grained.

BTW I'm happy that this tool is becoming useful. If it or something similar won't be included in the main glide and coreos (and other) projects are going to use it and you think it'll be worth I'll happily donate it to coreos to make it more visible.

**Comment by s-urbaniak** [comment]
@sgotti I think, regex is a good idea. Intuitively I'd love to see this functionality be present in `glide` itself so one doesn't have to install two separate binaries to manage vendored dependencies. Maybe @mattfarina could chime in to comment whether this functionality could be included in `glide` itself?

**Comment by sgotti** [comment]
@s-urbaniak Opened #15 . If you want to keep all the file ending with `json.in` you can use `--keep **/json.in`, for only a specified package `--keep github.com/appc/spec/ace/*.json.in`

**Comment by s-urbaniak** [comment]
closing in favor of #15

**Pull request closed without merging**
